<?php
// $Id: node.tpl.php,v 1.5 2007/10/11 09:51:29 goba Exp $
//print_r($node);


//*********TITLE**********
echo $node->title.'<br/>';

//*********UPDATED TIME**********
echo format_date($node->changed).'<br/>';

//*********BODY**********
echo $node->content['body']['#value'].'<br/>';

//*********TAXONOMY**********
foreach($node->taxonomy as $term)
{
	//print_r( $term);
	//if( $term->tid == 2)
		//print $term->name;
}

//*********IMAGE**********
$arr = parse_url($_SERVER['REQUEST_URI']);
$filePath = $arr['path'];
$imageLink = '';
foreach($node->field_pictorial_image as $currentImage)
{
	//folder workspace is needed only in DEVELOMENT 20100213  ************************************
	if($currentImage['view'] != '')
	{
		$src = '/workspace'.$filePath.$currentImage['filepath'];
		$thumbSrc = 'phpThumb/phpThumb.php?src='.$src.'&w=250&h=250';  //set maximum height AND width	
		$imageLink = '<img src="'.$thumbSrc.'" />';
		
//TICKBOX IMPLEMENTATION 
		//NOT WORKING thickBox needs the real image to display NOT the generated by phpThumb
		//$thickBoxSrc = 'phpThumb/phpThumb.php?src='.$src.'&w=500&h=500';			
		$thickBoxImageLink = '<a href="'.$src .'" class="thickbox" >'.$imageLink.'</a>';

		echo $thickBoxImageLink.'<br/><br/>';
		
	}
}

//********VIDEO***********
foreach($node->field_pictorial_video as $currentVideo)
{
	if($currentVideo['view'] != '')
	{
		echo $currentVideo['view'].'<br/>';
	}
}

//*******SOUND************
foreach($node->field_pictorial_sound as $currentSound)
{
	if($currentSound['view'] != '')
	{
		echo $currentSound['view'].'<br/>';
	}
}

?>
